In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [2]:
df=pd.read_csv('military.csv')
df.head(7)

,SR.NO,Country,Active military,Reserve military,Paramilitary,Total,"Per 1,000 capita(active)","Per 1,000 capita(total)"
0,1,Afghanistan,250000,75000,170000,495000,7.2,14.2
1,2,Albania,8000,0,0,8000,2.6,2.6
2,3,Algeria,130000,150000,187200,467200,3.1,11.2
3,4,Angola,107000,0,10000,117000,3.5,3.9
4,5,Antigua and Barbuda,180,80,0,260,1.9,2.7
5,6,Argentina,72100,0,31250,103350,1.6,2.3
6,7,Armenia,44800,210000,4300,259100,14.7,85.3

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 172 entries, 0 to 171
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   SR.NO                     172 non-null    int64
 1   Country                   172 non-null    str
 2   Active military           172 non-null    int64
 3   Reserve military          172 non-null    int64
 4   Paramilitary              172 non-null    int64
 5   Total                     172 non-null    int64
 6   Per 1,000 capita(active)  172 non-null    float64
 7   Per 1,000 capita(total)   172 non-null    float64
dtypes: float64(2), int64(5), str(1)
memory usage: 10.9 KB

In [4]:
df.describe()

,SR.NO,Active military,Reserve military,Paramilitary,Total,"Per 1,000 capita(active)","Per 1,000 capita(total)"
count,172.000000,1.720000e+02,1.720000e+02,1.720000e+02,1.720000e+02,172.000000,172.000000
mean,86.500000,1.187802e+05,1.456982e+05,1.111928e+05,3.756712e+05,4.141860,13.109884
std,49.796252,2.726087e+05,5.175997e+05,5.462052e+05,1.068150e+06,5.463124,29.381642
min,1.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000
25%,43.750000,8.950000e+03,0.000000e+00,0.000000e+00,1.241250e+04,1.600000,2.250000
50%,86.500000,2.665000e+04,4.000000e+01,5.000000e+03,5.122500e+04,2.700000,4.950000
75%,129.250000,1.210125e+05,5.650000e+04,2.720000e+04,2.534000e+05,4.450000,11.525000
max,172.000000,2.185000e+06,5.000000e+06,5.889000e+06,7.769000e+06,50.400000,306.100000

In [5]:
df.isnull().sum()

SR.NO                       0
Country                     0
Active military             0
Reserve military            0
Paramilitary                0
Total                       0
Per 1,000 capita(active)    0
Per 1,000 capita(total)     0
dtype: int64

In [6]:
p=df.sort_values(by="Per 1,000 capita(total)", ascending=False).head(5)
p

,SR.NO,Country,Active military,Reserve military,Paramilitary,Total,"Per 1,000 capita(active)","Per 1,000 capita(total)"
114,115,North Korea,1280000,600000,5889000,7769000,50.4,306.1
142,143,South Korea,599000,3100000,3013500,6712500,11.6,130.5
38,39,Cuba,49000,39000,1146500,1234500,4.4,110.9
6,7,Armenia,44800,210000,4300,259100,14.7,85.3
151,152,Taiwan (Republic of China),163000,1657000,11800,1831800,6.9,77.8

In [7]:
fig = px.bar(p, x="Country", y="Per 1,000 capita(total)", title="Top 5 Military Countries")
fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

In [ ]:
fig = px.bar(df.sort_values(by="Per 1,000 capita(total)", ascending=False).head(5),
             x="Country",
             y="Per 1,000 capita(total)",
             title="Top 5 Military Countries")

fig.show()

In [ ]:
c=df.sort_values(by="Per 1,000 capita(total)", ascending=True).head(5)
c

,SR.NO,Country,Active military,Reserve military,Paramilitary,Total,"Per 1,000 capita(active)","Per 1,000 capita(total)"
90,91,Libya,0,0,0,0,0.0,0.0
119,120,Palestine,0,0,0,0,0.0,0.0
66,67,Haiti,150,0,50,200,0.0,0.0
57,58,Gambia,800,0,0,800,0.4,0.4
89,90,Liberia,2010,0,0,2010,0.4,0.4

In [ ]:
fig = px.bar(df.sort_values(by="Per 1,000 capita(total)", ascending=True).head(5),
             x="Country",
             y="Per 1,000 capita(total)",
             title="Lowest 5 Military Countries")

fig.show()

In [ ]:
countries = ["Iran", "Israel", "United States"]

filtered = df[df["Country"].isin(countries)]
filtered

,SR.NO,Country,Active military,Reserve military,Paramilitary,Total,"Per 1,000 capita(active)","Per 1,000 capita(total)"
72,73,Iran,610000,350000,40000,1000000,7.3,12.0
75,76,Israel,169500,465000,8000,642500,20.1,76.3
164,165,United States,1328000,744950,0,2072950,4.0,6.3

In [ ]:
fig = px.scatter(
    filtered,
    x="Country",
    y="Per 1,000 capita(total)",
    size="Total",
    title="Military Personnel per 1000 Capita (Iran, Israel, USA)",
    hover_name="Country"
)

fig.show()

In [1]:
# ONE HOT ENCODING
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df=pd.DataFrame({"color":['red','blue','green','red']})

one= OneHotEncoder(sparse_output=False)

ones=one.fit_transform(df.loc[:,["color"]])

ones_df=pd.DataFrame(ones,columns=one.get_feature_names_out())

ones_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0

In [15]:
pd.concat([df,ones_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0

In [2]:
# LABEL ENCODER 
import pandas as pd
df= pd.DataFrame({'result':['good','bad','good','bad','excellent','bad','excellent','good','bad']})
df

      result
0       good
1        bad
2       good
3        bad
4  excellent
5        bad
6  excellent
7       good
8        bad

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [13]:
a=le.fit_transform(df.loc[:,'result'])
a

array([2, 0, 2, 0, 1, 0, 1, 2, 0])

In [11]:
df['result']=le.fit_transform(df.result)

In [12]:
df

   result
0       2
1       0
2       2
3       0
4       1
5       0
6       1
7       2
8       0