In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("Smartphone_Usage_Productivity_Dataset_50000.csv")

In [4]:
df.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9

In [6]:
df.shape

(50000, 13)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   User_ID                    50000 non-null  str
 1   Age                        50000 non-null  int64
 2   Gender                     50000 non-null  str
 3   Occupation                 50000 non-null  str
 4   Device_Type                50000 non-null  str
 5   Daily_Phone_Hours          50000 non-null  float64
 6   Social_Media_Hours         50000 non-null  float64
 7   Work_Productivity_Score    50000 non-null  int64
 8   Sleep_Hours                50000 non-null  float64
 9   Stress_Level               50000 non-null  int64
 10  App_Usage_Count            50000 non-null  int64
 11  Caffeine_Intake_Cups       50000 non-null  int64
 12  Weekend_Screen_Time_Hours  50000 non-null  float64
dtypes: float64(4), int64(5), str(4)
memory usage: 5.0 MB

In [8]:
df.describe()

,Age,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.00000,50000.000000,50000.000000
mean,39.034960,6.509116,4.267250,5.503760,6.497744,5.504500,32.43898,3.004580,8.006844
std,12.414877,3.170903,2.164743,2.874806,1.449551,2.871095,16.12151,1.996657,3.461300
min,18.000000,1.000000,0.500000,1.000000,4.000000,1.000000,5.00000,0.000000,2.000000
25%,28.000000,3.800000,2.400000,3.000000,5.200000,3.000000,18.00000,1.000000,5.000000
50%,39.000000,6.500000,4.300000,5.500000,6.500000,6.000000,32.00000,3.000000,8.000000
75%,50.000000,9.200000,6.100000,8.000000,7.800000,8.000000,46.00000,5.000000,11.000000
max,60.000000,12.000000,8.000000,10.000000,9.000000,10.000000,60.00000,6.000000,14.000000

In [9]:
df.Age.value_counts()

Age
54    1235
26    1221
43    1221
60    1214
45    1204
42    1204
38    1203
23    1193
56    1192
27    1185
33    1182
48    1182
44    1180
18    1180
46    1176
39    1170
24    1169
53    1169
41    1169
49    1168
55    1167
47    1165
19    1161
31    1161
20    1160
58    1159
29    1155
59    1151
37    1150
28    1149
52    1146
35    1143
34    1139
25    1138
36    1134
22    1133
32    1132
21    1122
50    1117
30    1113
57    1104
51    1104
40    1080
Name: count, dtype: int64

In [11]:
df.drop("Daily_Phone_Hours", axis=1, inplace=True)

In [12]:
df

,User_ID,Age,Gender,Occupation,Device_Type,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,U1,58,Male,Professional,Android,6.7,6,8.8,4,42,1,8.7
1,U2,25,Male,Professional,Android,1.5,5,6.4,1,51,3,5.1
2,U3,19,Male,Student,iOS,5.7,5,9.0,4,14,5,6.3
3,U4,35,Female,Business Owner,iOS,2.5,2,5.7,3,36,6,12.8
4,U5,33,Male,Freelancer,Android,1.3,4,5.7,3,37,5,9.9
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,U49996,44,Male,Business Owner,Android,5.4,5,6.6,1,11,5,3.0
49996,U49997,42,Other,Business Owner,Android,7.4,9,6.3,2,20,4,6.2
49997,U49998,27,Female,Freelancer,iOS,2.5,4,6.7,9,39,4,5.1
49998,U49999,41,Female,Business Owner,iOS,3.0,6,5.5,2,51,0,9.2
49999,U50000,46,Other,Freelancer,Android,2.8,3,5.4,1,54,5,6.9

In [19]:
df.Age.describe()

count    50000.000000
mean        39.034960
std         12.414877
min         18.000000
25%         28.000000
50%         39.000000
75%         50.000000
max         60.000000
Name: Age, dtype: float64

In [18]:
df.filter(items=["Age"])

       Age
0       58
1       25
2       19
3       35
4       33
...    ...
49995   44
49996   42
49997   27
49998   41
49999   46

[50000 rows x 1 columns]

In [17]:
df.loc[(df.loc[:,"Occupation"] == "Student") & (df.loc[:,"Work_Productivity_Score"] > 7) & (df.loc[:,"Gender"]=="Male")]

,User_ID,Age,Gender,Occupation,Device_Type,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
6,U7,26,Male,Student,iOS,6.1,8,6.7,3,5,3,2.9
159,U160,58,Male,Student,iOS,4.5,10,8.1,9,15,1,11.3
180,U181,23,Male,Student,Android,6.5,10,6.1,3,41,4,7.3
183,U184,22,Male,Student,iOS,5.6,8,4.9,2,52,2,7.7
268,U269,22,Male,Student,iOS,3.4,10,8.9,4,55,2,9.4
...,...,...,...,...,...,...,...,...,...,...,...,...
49900,U49901,31,Male,Student,Android,7.2,10,8.4,2,36,4,5.2
49932,U49933,33,Male,Student,iOS,6.4,10,4.6,10,9,1,8.1
49942,U49943,53,Male,Student,Android,0.7,8,7.3,6,10,0,7.7
49951,U49952,38,Male,Student,Android,7.9,8,8.4,2,53,5,10.4
49985,U49986,29,Male,Student,iOS,4.1,8,7.6,8,59,5,13.5