In [38]:
import pandas as pd
df=pd.read_csv("fake_news_dataset.csv")

# Mapping: 0 for Fake, 1 for Real
df['label'] = df['label'].map({'fake': 0, 'real': 1})

# Define your Features (X) and Target (y)
x = df['text']
y = df['label']

# Load datasets
# fake_df = pd.read_csv("Fake.csv")
# true_df = pd.read_csv("True.csv")

# # Add labels (0 = Fake, 1 = Real)
# fake_df["label"] = 0
# true_df["label"] = 1

# # Combine both datasets
# df = pd.concat([fake_df, true_df], axis=0)

# # Shuffle dataset
# df = df.sample(frac=1).reset_index(drop=True)

# Show first rows
df.head()

,title,text,date,source,author,category,label
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,1
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,0
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,0
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,0
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,0

In [39]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   title     20000 non-null  str
 1   text      20000 non-null  str
 2   date      20000 non-null  str
 3   source    19000 non-null  str
 4   author    19000 non-null  str
 5   category  20000 non-null  str
 6   label     20000 non-null  int64
dtypes: int64(1), str(6)
memory usage: 1.1 MB

In [40]:
import nltk

In [41]:

import re

def clean_text(text):
    text = text.lower()                  # lowercase
    text = re.sub(r'[^a-zA-Z]', ' ', text)  # remove punctuation & numbers
    text = re.sub(r'\s+', ' ', text)        # remove extra spaces
    return text

df['clean_text'] = df['text'].apply(clean_text)
print(df[['text', 'clean_text']])

                                                    text  \
0      more tax development both store agreement lawy...
1      probably guess western behind likely next inve...
2      them identify forward present success risk sev...
3      phone which item yard Republican safe where po...
4      wonder myself fact difficult course forget exa...
...                                                  ...
19995  hit and television I change very our happy doo...
19996  fear most meet rock even sea value design stan...
19997  activity loss very provide eye west create wha...
19998  term point general common training watch respo...
19999  remain pressure glass me six senior though nor...

                                              clean_text
0      more tax development both store agreement lawy...
1      probably guess western behind likely next inve...
2      them identify forward present success risk sev...
3      phone which item yard republican safe where po...
4      wonder myself fact difficult course forget exa...
...                                                  ...
19995  hit and television i change very our happy doo...
19996  fear most meet rock even sea value design stan...
19997  activity loss very provide eye west create wha...
19998  term point general common training watch respo...
19999  remain pressure glass me six senior though nor...

[20000 rows x 2 columns]

In [42]:
df

,title,text,date,source,author,category,label,clean_text
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,1,more tax development both store agreement lawy...
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,0,probably guess western behind likely next inve...
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,0,them identify forward present success risk sev...
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,0,phone which item yard republican safe where po...
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,0,wonder myself fact difficult course forget exa...
...,...,...,...,...,...,...,...,...
19995,House party born.,hit and television I change very our happy doo...,2024-12-04,BBC,Gary Miles,Entertainment,0,hit and television i change very our happy doo...
19996,Though nation people maybe price box.,fear most meet rock even sea value design stan...,2024-05-26,Daily News,Maria Mcbride,Entertainment,1,fear most meet rock even sea value design stan...
19997,Yet exist with experience unit.,activity loss very provide eye west create wha...,2023-04-17,BBC,Kristen Franklin,Entertainment,1,activity loss very provide eye west create wha...
19998,School wide itself item.,term point general common training watch respo...,2024-06-30,Reuters,David Wise,Health,0,term point general common training watch respo...
19999,Offer chair cover senior born.,remain pressure glass me six senior though nor...,2024-01-24,Daily News,James Peterson,Health,0,remain pressure glass me six senior though nor...

In [43]:
from nltk.tokenize import word_tokenize

df['tokens'] = df['clean_text'].apply(word_tokenize)
print(df['tokens'])
df

0        [more, tax, development, both, store, agreemen...
1        [probably, guess, western, behind, likely, nex...
2        [them, identify, forward, present, success, ri...
3        [phone, which, item, yard, republican, safe, w...
4        [wonder, myself, fact, difficult, course, forg...
                               ...
19995    [hit, and, television, i, change, very, our, h...
19996    [fear, most, meet, rock, even, sea, value, des...
19997    [activity, loss, very, provide, eye, west, cre...
19998    [term, point, general, common, training, watch...
19999    [remain, pressure, glass, me, six, senior, tho...
Name: tokens, Length: 20000, dtype: object

,title,text,date,source,author,category,label,clean_text,tokens
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,1,more tax development both store agreement lawy...,"[more, tax, development, both, store, agreemen..."
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,0,probably guess western behind likely next inve...,"[probably, guess, western, behind, likely, nex..."
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,0,them identify forward present success risk sev...,"[them, identify, forward, present, success, ri..."
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,0,phone which item yard republican safe where po...,"[phone, which, item, yard, republican, safe, w..."
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,0,wonder myself fact difficult course forget exa...,"[wonder, myself, fact, difficult, course, forg..."
...,...,...,...,...,...,...,...,...,...
19995,House party born.,hit and television I change very our happy doo...,2024-12-04,BBC,Gary Miles,Entertainment,0,hit and television i change very our happy doo...,"[hit, and, television, i, change, very, our, h..."
19996,Though nation people maybe price box.,fear most meet rock even sea value design stan...,2024-05-26,Daily News,Maria Mcbride,Entertainment,1,fear most meet rock even sea value design stan...,"[fear, most, meet, rock, even, sea, value, des..."
19997,Yet exist with experience unit.,activity loss very provide eye west create wha...,2023-04-17,BBC,Kristen Franklin,Entertainment,1,activity loss very provide eye west create wha...,"[activity, loss, very, provide, eye, west, cre..."
19998,School wide itself item.,term point general common training watch respo...,2024-06-30,Reuters,David Wise,Health,0,term point general common training watch respo...,"[term, point, general, common, training, watch..."
19999,Offer chair cover senior born.,remain pressure glass me six senior though nor...,2024-01-24,Daily News,James Peterson,Health,0,remain pressure glass me six senior though nor...,"[remain, pressure, glass, me, six, senior, tho..."

In [44]:
from nltk.tokenize import sent_tokenize
df['sentence_tokens']=df['clean_text'].apply(sent_tokenize)

In [45]:
print(df['sentence_tokens'])
df

0        [more tax development both store agreement law...
1        [probably guess western behind likely next inv...
2        [them identify forward present success risk se...
3        [phone which item yard republican safe where p...
4        [wonder myself fact difficult course forget ex...
                               ...
19995    [hit and television i change very our happy do...
19996    [fear most meet rock even sea value design sta...
19997    [activity loss very provide eye west create wh...
19998    [term point general common training watch resp...
19999    [remain pressure glass me six senior though no...
Name: sentence_tokens, Length: 20000, dtype: object

,title,text,date,source,author,category,label,clean_text,tokens,sentence_tokens
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,1,more tax development both store agreement lawy...,"[more, tax, development, both, store, agreemen...",[more tax development both store agreement law...
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,0,probably guess western behind likely next inve...,"[probably, guess, western, behind, likely, nex...",[probably guess western behind likely next inv...
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,0,them identify forward present success risk sev...,"[them, identify, forward, present, success, ri...",[them identify forward present success risk se...
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,0,phone which item yard republican safe where po...,"[phone, which, item, yard, republican, safe, w...",[phone which item yard republican safe where p...
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,0,wonder myself fact difficult course forget exa...,"[wonder, myself, fact, difficult, course, forg...",[wonder myself fact difficult course forget ex...
...,...,...,...,...,...,...,...,...,...,...
19995,House party born.,hit and television I change very our happy doo...,2024-12-04,BBC,Gary Miles,Entertainment,0,hit and television i change very our happy doo...,"[hit, and, television, i, change, very, our, h...",[hit and television i change very our happy do...
19996,Though nation people maybe price box.,fear most meet rock even sea value design stan...,2024-05-26,Daily News,Maria Mcbride,Entertainment,1,fear most meet rock even sea value design stan...,"[fear, most, meet, rock, even, sea, value, des...",[fear most meet rock even sea value design sta...
19997,Yet exist with experience unit.,activity loss very provide eye west create wha...,2023-04-17,BBC,Kristen Franklin,Entertainment,1,activity loss very provide eye west create wha...,"[activity, loss, very, provide, eye, west, cre...",[activity loss very provide eye west create wh...
19998,School wide itself item.,term point general common training watch respo...,2024-06-30,Reuters,David Wise,Health,0,term point general common training watch respo...,"[term, point, general, common, training, watch...",[term point general common training watch resp...
19999,Offer chair cover senior born.,remain pressure glass me six senior though nor...,2024-01-24,Daily News,James Peterson,Health,0,remain pressure glass me six senior though nor...,"[remain, pressure, glass, me, six, senior, tho...",[remain pressure glass me six senior though no...

In [46]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['no_stopwords'] = df['tokens'].apply(remove_stopwords)
print(df['no_stopwords'])
df

0        [tax, development, store, agreement, lawyer, h...
1        [probably, guess, western, behind, likely, nex...
2        [identify, forward, present, success, risk, se...
3        [phone, item, yard, republican, safe, police, ...
4        [wonder, fact, difficult, course, forget, exac...
                               ...
19995    [hit, television, change, happy, door, wide, e...
19996    [fear, meet, rock, even, sea, value, design, s...
19997    [activity, loss, provide, eye, west, create, w...
19998    [term, point, general, common, training, watch...
19999    [remain, pressure, glass, six, senior, though,...
Name: no_stopwords, Length: 20000, dtype: object

,title,text,date,source,author,category,label,clean_text,tokens,sentence_tokens,no_stopwords
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,1,more tax development both store agreement lawy...,"[more, tax, development, both, store, agreemen...",[more tax development both store agreement law...,"[tax, development, store, agreement, lawyer, h..."
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,0,probably guess western behind likely next inve...,"[probably, guess, western, behind, likely, nex...",[probably guess western behind likely next inv...,"[probably, guess, western, behind, likely, nex..."
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,0,them identify forward present success risk sev...,"[them, identify, forward, present, success, ri...",[them identify forward present success risk se...,"[identify, forward, present, success, risk, se..."
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,0,phone which item yard republican safe where po...,"[phone, which, item, yard, republican, safe, w...",[phone which item yard republican safe where p...,"[phone, item, yard, republican, safe, police, ..."
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,0,wonder myself fact difficult course forget exa...,"[wonder, myself, fact, difficult, course, forg...",[wonder myself fact difficult course forget ex...,"[wonder, fact, difficult, course, forget, exac..."
...,...,...,...,...,...,...,...,...,...,...,...
19995,House party born.,hit and television I change very our happy doo...,2024-12-04,BBC,Gary Miles,Entertainment,0,hit and television i change very our happy doo...,"[hit, and, television, i, change, very, our, h...",[hit and television i change very our happy do...,"[hit, television, change, happy, door, wide, e..."
19996,Though nation people maybe price box.,fear most meet rock even sea value design stan...,2024-05-26,Daily News,Maria Mcbride,Entertainment,1,fear most meet rock even sea value design stan...,"[fear, most, meet, rock, even, sea, value, des...",[fear most meet rock even sea value design sta...,"[fear, meet, rock, even, sea, value, design, s..."
19997,Yet exist with experience unit.,activity loss very provide eye west create wha...,2023-04-17,BBC,Kristen Franklin,Entertainment,1,activity loss very provide eye west create wha...,"[activity, loss, very, provide, eye, west, cre...",[activity loss very provide eye west create wh...,"[activity, loss, provide, eye, west, create, w..."
19998,School wide itself item.,term point general common training watch respo...,2024-06-30,Reuters,David Wise,Health,0,term point general common training watch respo...,"[term, point, general, common, training, watch...",[term point general common training watch resp...,"[term, point, general, common, training, watch..."
19999,Offer chair cover senior born.,remain pressure glass me six senior though nor...,2024-01-24,Daily News,James Peterson,Health,0,remain pressure glass me six senior though nor...,"[remain, pressure, glass, me, six, senior, tho...",[remain pressure glass me six senior though no...,"[remain, pressure, glass, six, senior, though,..."

In [47]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatization(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df['lemmatized'] = df['no_stopwords'].apply(lemmatization)
print(df['lemmatized'])
df

0        [tax, development, store, agreement, lawyer, h...
1        [probably, guess, western, behind, likely, nex...
2        [identify, forward, present, success, risk, se...
3        [phone, item, yard, republican, safe, police, ...
4        [wonder, fact, difficult, course, forget, exac...
                               ...
19995    [hit, television, change, happy, door, wide, e...
19996    [fear, meet, rock, even, sea, value, design, s...
19997    [activity, loss, provide, eye, west, create, w...
19998    [term, point, general, common, training, watch...
19999    [remain, pressure, glass, six, senior, though,...
Name: lemmatized, Length: 20000, dtype: object

,title,text,date,source,author,category,label,clean_text,tokens,sentence_tokens,no_stopwords,lemmatized
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,1,more tax development both store agreement lawy...,"[more, tax, development, both, store, agreemen...",[more tax development both store agreement law...,"[tax, development, store, agreement, lawyer, h...","[tax, development, store, agreement, lawyer, h..."
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,0,probably guess western behind likely next inve...,"[probably, guess, western, behind, likely, nex...",[probably guess western behind likely next inv...,"[probably, guess, western, behind, likely, nex...","[probably, guess, western, behind, likely, nex..."
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,0,them identify forward present success risk sev...,"[them, identify, forward, present, success, ri...",[them identify forward present success risk se...,"[identify, forward, present, success, risk, se...","[identify, forward, present, success, risk, se..."
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,0,phone which item yard republican safe where po...,"[phone, which, item, yard, republican, safe, w...",[phone which item yard republican safe where p...,"[phone, item, yard, republican, safe, police, ...","[phone, item, yard, republican, safe, police, ..."
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,0,wonder myself fact difficult course forget exa...,"[wonder, myself, fact, difficult, course, forg...",[wonder myself fact difficult course forget ex...,"[wonder, fact, difficult, course, forget, exac...","[wonder, fact, difficult, course, forget, exac..."
...,...,...,...,...,...,...,...,...,...,...,...,...
19995,House party born.,hit and television I change very our happy doo...,2024-12-04,BBC,Gary Miles,Entertainment,0,hit and television i change very our happy doo...,"[hit, and, television, i, change, very, our, h...",[hit and television i change very our happy do...,"[hit, television, change, happy, door, wide, e...","[hit, television, change, happy, door, wide, e..."
19996,Though nation people maybe price box.,fear most meet rock even sea value design stan...,2024-05-26,Daily News,Maria Mcbride,Entertainment,1,fear most meet rock even sea value design stan...,"[fear, most, meet, rock, even, sea, value, des...",[fear most meet rock even sea value design sta...,"[fear, meet, rock, even, sea, value, design, s...","[fear, meet, rock, even, sea, value, design, s..."
19997,Yet exist with experience unit.,activity loss very provide eye west create wha...,2023-04-17,BBC,Kristen Franklin,Entertainment,1,activity loss very provide eye west create wha...,"[activity, loss, very, provide, eye, west, cre...",[activity loss very provide eye west create wh...,"[activity, loss, provide, eye, west, create, w...","[activity, loss, provide, eye, west, create, w..."
19998,School wide itself item.,term point general common training watch respo...,2024-06-30,Reuters,David Wise,Health,0,term point general common training watch respo...,"[term, point, general, common, training, watch...",[term point general common training watch resp...,"[term, point, general, common, training, watch...","[term, point, general, common, training, watch..."
19999,Offer chair cover senior born.,remain pressure glass me six senior though nor...,2024-01-24,Daily News,James Peterson,Health,0,remain pressure glass me six senior though nor...,"[remain, pressure, glass, me, six, senior, tho...",[remain pressure glass me six senior though no...,"[remain, pressure, glass, six, senior, though,...","[remain, pressure, glass, six, senior, though,..."

In [48]:
df['final_text'] = df['lemmatized'].apply(lambda x: " ".join(x))
print(df['final_text'])
df

0        tax development store agreement lawyer hear ou...
1        probably guess western behind likely next inve...
2        identify forward present success risk several ...
3        phone item yard republican safe police identif...
4        wonder fact difficult course forget exactly pa...
                               ...
19995    hit television change happy door wide east per...
19996    fear meet rock even sea value design standard ...
19997    activity loss provide eye west create whatever...
19998    term point general common training watch respo...
19999    remain pressure glass six senior though look o...
Name: final_text, Length: 20000, dtype: str

,title,text,date,source,author,category,label,clean_text,tokens,sentence_tokens,no_stopwords,lemmatized,final_text
0,Foreign Democrat final.,more tax development both store agreement lawy...,2023-03-10,NY Times,Paula George,Politics,1,more tax development both store agreement lawy...,"[more, tax, development, both, store, agreemen...",[more tax development both store agreement law...,"[tax, development, store, agreement, lawyer, h...","[tax, development, store, agreement, lawyer, h...",tax development store agreement lawyer hear ou...
1,To offer down resource great point.,probably guess western behind likely next inve...,2022-05-25,Fox News,Joseph Hill,Politics,0,probably guess western behind likely next inve...,"[probably, guess, western, behind, likely, nex...",[probably guess western behind likely next inv...,"[probably, guess, western, behind, likely, nex...","[probably, guess, western, behind, likely, nex...",probably guess western behind likely next inve...
2,Himself church myself carry.,them identify forward present success risk sev...,2022-09-01,CNN,Julia Robinson,Business,0,them identify forward present success risk sev...,"[them, identify, forward, present, success, ri...",[them identify forward present success risk se...,"[identify, forward, present, success, risk, se...","[identify, forward, present, success, risk, se...",identify forward present success risk several ...
3,You unit its should.,phone which item yard Republican safe where po...,2023-02-07,Reuters,Mr. David Foster DDS,Science,0,phone which item yard republican safe where po...,"[phone, which, item, yard, republican, safe, w...",[phone which item yard republican safe where p...,"[phone, item, yard, republican, safe, police, ...","[phone, item, yard, republican, safe, police, ...",phone item yard republican safe police identif...
4,Billion believe employee summer how.,wonder myself fact difficult course forget exa...,2023-04-03,CNN,Austin Walker,Technology,0,wonder myself fact difficult course forget exa...,"[wonder, myself, fact, difficult, course, forg...",[wonder myself fact difficult course forget ex...,"[wonder, fact, difficult, course, forget, exac...","[wonder, fact, difficult, course, forget, exac...",wonder fact difficult course forget exactly pa...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,House party born.,hit and television I change very our happy doo...,2024-12-04,BBC,Gary Miles,Entertainment,0,hit and television i change very our happy doo...,"[hit, and, television, i, change, very, our, h...",[hit and television i change very our happy do...,"[hit, television, change, happy, door, wide, e...","[hit, television, change, happy, door, wide, e...",hit television change happy door wide east per...
19996,Though nation people maybe price box.,fear most meet rock even sea value design stan...,2024-05-26,Daily News,Maria Mcbride,Entertainment,1,fear most meet rock even sea value design stan...,"[fear, most, meet, rock, even, sea, value, des...",[fear most meet rock even sea value design sta...,"[fear, meet, rock, even, sea, value, design, s...","[fear, meet, rock, even, sea, value, design, s...",fear meet rock even sea value design standard ...
19997,Yet exist with experience unit.,activity loss very provide eye west create wha...,2023-04-17,BBC,Kristen Franklin,Entertainment,1,activity loss very provide eye west create wha...,"[activity, loss, very, provide, eye, west, cre...",[activity loss very provide eye west create wh...,"[activity, loss, provide, eye, west, create, w...","[activity, loss, provide, eye, west, create, w...",activity loss provide eye west create whatever...
19998,School wide itself item.,term point general common training watch respo...,2024-06-30,Reuters,David Wise,Health,0,term point general common training watch respo...,"[term, point, general, common, training, watch...",[term point general common training watch resp...,"[term, point, general, common, training, watch...","[term, point, general, common, training, watch...",term point general common training watch respo...
19999,Offer chair cover senior born.,remain pressure glass me six senior though nor...,2024-01-24,Daily News,James Peterson,Health,0,remain pressure glass me six senior though nor...,"[remain, pressure, glass, me, six, senior, tho...",[remain pressure glass me six senior though no...,"[remain, pressure, glass, six, senior, though,...","[remain, pressure, glass, six, senior, though,...",remain pressure glass six senior though look o...

In [49]:
df.drop(columns=['text','clean_text','tokens','sentence_tokens','no_stopwords','lemmatized'])

,title,date,source,author,category,label,final_text
0,Foreign Democrat final.,2023-03-10,NY Times,Paula George,Politics,1,tax development store agreement lawyer hear ou...
1,To offer down resource great point.,2022-05-25,Fox News,Joseph Hill,Politics,0,probably guess western behind likely next inve...
2,Himself church myself carry.,2022-09-01,CNN,Julia Robinson,Business,0,identify forward present success risk several ...
3,You unit its should.,2023-02-07,Reuters,Mr. David Foster DDS,Science,0,phone item yard republican safe police identif...
4,Billion believe employee summer how.,2023-04-03,CNN,Austin Walker,Technology,0,wonder fact difficult course forget exactly pa...
...,...,...,...,...,...,...,...
19995,House party born.,2024-12-04,BBC,Gary Miles,Entertainment,0,hit television change happy door wide east per...
19996,Though nation people maybe price box.,2024-05-26,Daily News,Maria Mcbride,Entertainment,1,fear meet rock even sea value design standard ...
19997,Yet exist with experience unit.,2023-04-17,BBC,Kristen Franklin,Entertainment,1,activity loss provide eye west create whatever...
19998,School wide itself item.,2024-06-30,Reuters,David Wise,Health,0,term point general common training watch respo...
19999,Offer chair cover senior born.,2024-01-24,Daily News,James Peterson,Health,0,remain pressure glass six senior though look o...

In [50]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X = cv.fit_transform(df['final_text'])
y = df['label']

print("Vocabulary:", cv.vocabulary_)
print("Feature Matrix:\n", X)

Vocabulary: {'tax': 762, 'development': 197, 'store': 737, 'agreement': 21, 'lawyer': 398, 'hear': 335, 'outside': 520, 'continue': 160, 'reach': 603, 'difference': 198, 'yeah': 862, 'figure': 272, 'power': 566, 'fear': 266, 'identify': 356, 'protect': 585, 'security': 661, 'great': 318, 'national': 481, 'nothing': 499, 'fast': 264, 'story': 738, 'late': 394, 'nearly': 485, 'bit': 86, 'cost': 162, 'tough': 792, 'since': 687, 'question': 594, 'almost': 25, 'future': 304, 'young': 866, 'conference': 155, 'behind': 77, 'ahead': 22, 'building': 101, 'teach': 763, 'million': 459, 'box': 94, 'receive': 611, 'mr': 475, 'risk': 641, 'benefit': 79, 'month': 468, 'compare': 151, 'environment': 236, 'class': 138, 'imagine': 358, 'vote': 822, 'community': 149, 'reason': 610, 'set': 673, 'idea': 355, 'answer': 38, 'many': 438, 'purpose': 590, 'deep': 186, 'training': 797, 'game': 305, 'true': 805, 'language': 391, 'garden': 306, 'partner': 530, 'result': 635, 'face': 258, 'military': 458, 'discover': 204, 'data': 178, 'glass': 313, 'bed': 74, 'maintain': 430, 'test': 772, 'way': 830, 'across': 5, 'top': 790, 'culture': 172, 'yes': 864, 'decision': 185, 'hope': 344, 'necessary': 486, 'trade': 795, 'organization': 518, 'talk': 760, 'debate': 182, 'peace': 536, 'stay': 732, 'six': 694, 'wide': 842, 'write': 858, 'several': 675, 'fight': 271, 'billion': 85, 'common': 148, 'personal': 543, 'church': 133, 'establish': 239, 'kind': 386, 'hundred': 353, 'hotel': 347, 'cut': 176, 'sister': 690, 'audience': 57, 'sound': 711, 'case': 114, 'within': 848, 'information': 369, 'trouble': 804, 'responsibility': 633, 'force': 292, 'people': 537, 'bar': 69, 'miss': 462, 'others': 519, 'sometimes': 706, 'build': 100, 'room': 645, 'interesting': 374, 'however': 350, 'charge': 128, 'especially': 238, 'north': 497, 'travel': 798, 'industry': 368, 'including': 363, 'ten': 769, 'black': 87, 'series': 669, 'place': 549, 'age': 16, 'soldier': 702, 'early': 215, 'middle': 456, 'would': 857, 'along': 27, 'money': 467, 'significant': 683, 'song': 708, 'poor': 560, 'free': 299, 'want': 826, 'thank': 773, 'cultural': 171, 'range': 600, 'shoulder': 679, 'rest': 634, 'movie': 474, 'political': 558, 'past': 533, 'leader': 401, 'edge': 221, 'professor': 581, 'determine': 195, 'law': 397, 'act': 6, 'change': 126, 'prove': 586, 'say': 650, 'notice': 500, 'open': 513, 'director': 203, 'argue': 45, 'economic': 219, 'seven': 674, 'matter': 442, 'season': 657, 'probably': 575, 'guess': 324, 'western': 836, 'likely': 414, 'next': 493, 'investment': 377, 'consumer': 158, 'wrong': 860, 'exactly': 249, 'attack': 54, 'daughter': 179, 'executive': 251, 'tonight': 789, 'factor': 260, 'push': 591, 'pas': 532, 'field': 270, 'firm': 282, 'accept': 2, 'represent': 626, 'computer': 152, 'win': 844, 'small': 698, 'character': 127, 'total': 791, 'air': 23, 'must': 478, 'difficult': 200, 'green': 319, 'writer': 859, 'adult': 14, 'though': 778, 'individual': 367, 'learn': 402, 'interview': 376, 'available': 60, 'drug': 214, 'group': 321, 'produce': 577, 'large': 392, 'wish': 847, 'find': 278, 'even': 240, 'medium': 448, 'nature': 483, 'last': 393, 'project': 583, 'special': 717, 'stand': 725, 'lead': 400, 'ball': 67, 'contain': 159, 'road': 642, 'history': 340, 'customer': 175, 'throw': 784, 'tell': 768, 'discus': 205, 'remain': 623, 'view': 819, 'morning': 469, 'put': 592, 'mouth': 471, 'serve': 671, 'certain': 121, 'two': 810, 'structure': 742, 'skin': 697, 'yard': 861, 'position': 563, 'suffer': 751, 'someone': 704, 'ok': 509, 'mind': 460, 'something': 705, 'theory': 774, 'letter': 409, 'seat': 658, 'fall': 261, 'authority': 59, 'get': 310, 'man': 434, 'loss': 424, 'bring': 97, 'friend': 300, 'final': 275, 'occur': 502, 'summer': 753, 'similar': 684, 'best': 80, 'area': 44, 'real': 606, 'still': 734, 'scientist': 654, 'social': 700, 'everybody': 245, 'front': 301, 'direction': 202, 'arrive': 48, 'baby': 63, 'already': 28, 'size': 695, 'financial': 277, 'clear': 139, 'whether': 838, 'save': 649, 'realize': 608, 'right': 639, 'break': 96, 'quickly': 595, 'music': 477, 'price': 574, 'prevent': 573, 'truth': 806, 'effort': 224, 'strong': 741, 'everything': 247, 'also': 29, 'body': 91, 'together': 788, 'least': 403, 'research': 629, 'dog': 208, 'mean': 445, 'near': 484, 'interest': 373, 'unit': 813, 'seek': 663, 'blood': 88, 'husband': 354, 'teacher': 764, 'apply': 42, 'fill': 273, 'south': 713, 'woman': 850, 'television': 767, 'worry': 856, 'style': 746, 'maybe': 444, 'ability': 0, 'relate': 620, 'amount': 34, 'actually': 9, 'quite': 596, 'whose': 841, 'smile': 699, 'student': 743, 'current': 174, 'mother': 470, 'simply': 686, 'gun': 325, 'republican': 627, 'none': 496, 'market': 439, 'admit': 13, 'knowledge': 389, 'animal': 36, 'majority': 432, 'product': 578, 'attorney': 56, 'approach': 43, 'forward': 297, 'present': 569, 'success': 748, 'pull': 589, 'choose': 132, 'born': 93, 'election': 227, 'plant': 551, 'thing': 775, 'side': 681, 'soon': 709, 'guy': 326, 'practice': 567, 'dream': 211, 'despite': 193, 'less': 407, 'artist': 51, 'minute': 461, 'although': 30, 'eye': 257, 'make': 433, 'back': 64, 'care': 111, 'thus': 785, 'much': 476, 'college': 145, 'night': 495, 'name': 479, 'instead': 371, 'follow': 289, 'long': 421, 'president': 570, 'like': 413, 'attention': 55, 'crime': 170, 'recently': 613, 'need': 487, 'commercial': 147, 'address': 11, 'send': 666, 'religious': 622, 'join': 382, 'opportunity': 515, 'degree': 188, 'throughout': 783, 'response': 632, 'toward': 793, 'card': 110, 'state': 729, 'arm': 46, 'low': 426, 'threat': 781, 'property': 584, 'eat': 218, 'bill': 84, 'public': 588, 'trip': 803, 'note': 498, 'hair': 327, 'defense': 187, 'citizen': 134, 'rather': 602, 'believe': 78, 'level': 410, 'wall': 825, 'short': 678, 'respond': 631, 'town': 794, 'return': 636, 'discussion': 206, 'never': 489, 'entire': 235, 'develop': 196, 'fire': 281, 'modern': 465, 'suggest': 752, 'could': 163, 'work': 853, 'office': 504, 'door': 209, 'fund': 303, 'ready': 605, 'role': 644, 'everyone': 246, 'often': 507, 'father': 265, 'point': 555, 'choice': 131, 'meet': 449, 'think': 776, 'treatment': 800, 'inside': 370, 'assume': 53, 'check': 129, 'senior': 667, 'condition': 154, 'trial': 802, 'foot': 291, 'explain': 256, 'police': 556, 'kid': 385, 'share': 677, 'deal': 181, 'southern': 714, 'help': 338, 'cause': 116, 'manager': 437, 'tv': 809, 'ago': 19, 'word': 852, 'reality': 607, 'affect': 15, 'phone': 544, 'item': 380, 'safe': 648, 'either': 226, 'participant': 527, 'human': 352, 'enough': 233, 'offer': 503, 'high': 339, 'paper': 524, 'cover': 168, 'service': 672, 'film': 274, 'agree': 20, 'moment': 466, 'positive': 564, 'task': 761, 'finally': 276, 'traditional': 796, 'single': 689, 'wear': 831, 'speech': 719, 'couple': 165, 'somebody': 703, 'pm': 554, 'remember': 624, 'situation': 693, 'visit': 820, 'general': 308, 'society': 701, 'player': 553, 'play': 552, 'page': 522, 'brother': 98, 'window': 846, 'indeed': 365, 'energy': 231, 'lose': 423, 'stage': 724, 'perhaps': 541, 'hot': 346, 'carry': 113, 'form': 295, 'meeting': 450, 'sure': 755, 'parent': 525, 'walk': 824, 'whatever': 837, 'collection': 144, 'team': 765, 'health': 334, 'full': 302, 'white': 839, 'laugh': 396, 'line': 415, 'exist': 252, 'statement': 730, 'try': 807, 'pattern': 534, 'claim': 137, 'chance': 125, 'else': 228, 'decade': 183, 'sing': 688, 'rich': 638, 'employee': 229, 'catch': 115, 'time': 786, 'official': 506, 'family': 262, 'camera': 105, 'wait': 823, 'art': 49, 'detail': 194, 'sort': 710, 'another': 37, 'let': 408, 'forget': 294, 'third': 777, 'evidence': 248, 'end': 230, 'old': 510, 'sign': 682, 'population': 562, 'war': 827, 'include': 362, 'school': 652, 'eight': 225, 'might': 457, 'bag': 66, 'worker': 854, 'institution': 372, 'food': 290, 'per': 538, 'chair': 123, 'reflect': 618, 'speak': 716, 'officer': 505, 'understand': 812, 'good': 316, 'weight': 833, 'movement': 473, 'main': 429, 'account': 4, 'gas': 307, 'wonder': 851, 'fact': 259, 'course': 166, 'sell': 665, 'various': 818, 'first': 283, 'year': 863, 'involve': 378, 'effect': 223, 'look': 422, 'particularly': 529, 'agency': 17, 'relationship': 621, 'home': 343, 'physical': 545, 'recent': 612, 'world': 855, 'beyond': 82, 'bad': 65, 'memory': 452, 'anyone': 39, 'week': 832, 'sport': 721, 'value': 817, 'politics': 559, 'upon': 814, 'administration': 12, 'space': 715, 'doctor': 207, 'activity': 8, 'child': 130, 'around': 47, 'number': 501, 'process': 576, 'city': 135, 'site': 692, 'party': 531, 'watch': 828, 'beat': 71, 'quality': 593, 'become': 73, 'expect': 253, 'possible': 565, 'star': 727, 'girl': 311, 'four': 298, 'radio': 598, 'budget': 99, 'thousand': 780, 'base': 70, 'support': 754, 'court': 167, 'reduce': 617, 'score': 655, 'anything': 40, 'management': 436, 'focus': 288, 'machine': 427, 'run': 647, 'shake': 676, 'goal': 315, 'turn': 808, 'campaign': 106, 'medical': 447, 'leave': 404, 'analysis': 35, 'one': 511, 'kitchen': 387, 'new': 490, 'car': 109, 'among': 33, 'country': 164, 'pressure': 571, 'american': 32, 'nation': 480, 'stuff': 745, 'successful': 749, 'type': 811, 'tree': 801, 'keep': 383, 'recognize': 614, 'piece': 548, 'draw': 210, 'blue': 89, 'fish': 284, 'former': 296, 'rule': 646, 'region': 619, 'show': 680, 'newspaper': 492, 'hour': 348, 'option': 516, 'different': 199, 'five': 285, 'control': 161, 'half': 328, 'major': 431, 'according': 3, 'business': 102, 'local': 420, 'mission': 463, 'voice': 821, 'marriage': 440, 'coach': 142, 'appear': 41, 'heart': 336, 'usually': 816, 'mention': 453, 'issue': 379, 'concern': 153, 'capital': 108, 'every': 244, 'picture': 547, 'environmental': 237, 'education': 222, 'later': 395, 'color': 146, 'stop': 736, 'hand': 329, 'read': 604, 'enter': 234, 'life': 411, 'model': 464, 'spend': 720, 'democratic': 190, 'strategy': 739, 'house': 349, 'give': 312, 'ground': 320, 'provide': 587, 'staff': 723, 'station': 731, 'surface': 756, 'technology': 766, 'tend': 770, 'hard': 332, 'drive': 212, 'simple': 685, 'allow': 24, 'go': 314, 'study': 744, 'stock': 735, 'happen': 330, 'news': 491, 'yet': 865, 'particular': 528, 'consider': 157, 'example': 250, 'may': 443, 'street': 740, 'section': 660, 'standard': 726, 'call': 104, 'list': 416, 'center': 118, 'impact': 359, 'big': 83, 'increase': 364, 'book': 92, 'land': 390, 'congress': 156, 'treat': 799, 'rock': 643, 'fine': 279, 'lot': 425, 'dinner': 201, 'lay': 399, 'key': 384, 'economy': 220, 'feel': 268, 'foreign': 293, 'require': 628, 'heavy': 337, 'table': 758, 'article': 50, 'author': 58, 'job': 381, 'term': 771, 'measure': 446, 'subject': 747, 'far': 263, 'evening': 241, 'three': 782, 'alone': 26, 'order': 517, 'plan': 550, 'design': 192, 'feeling': 269, 'see': 662, 'specific': 718, 'perform': 539, 'serious': 670, 'drop': 213, 'science': 653, 'company': 150, 'nice': 494, 'huge': 351, 'begin': 75, 'challenge': 124, 'production': 579, 'today': 787, 'leg': 406, 'performance': 540, 'able': 1, 'hit': 341, 'indicate': 366, 'rate': 601, 'use': 815, 'important': 360, 'manage': 435, 'operation': 514, 'person': 542, 'cell': 117, 'pick': 546, 'professional': 580, 'add': 10, 'natural': 482, 'move': 472, 'clearly': 140, 'international': 375, 'civil': 136, 'cup': 173, 'second': 659, 'ever': 243, 'beautiful': 72, 'listen': 417, 'magazine': 428, 'century': 120, 'little': 418, 'popular': 561, 'boy': 95, 'generation': 309, 'central': 119, 'race': 597, 'policy': 557, 'image': 357, 'certainly': 122, 'spring': 722, 'method': 455, 'left': 405, 'sea': 656, 'onto': 512, 'close': 141, 'candidate': 107, 'material': 441, 'agent': 18, 'enjoy': 232, 'buy': 103, 'ask': 52, 'experience': 254, 'part': 526, 'water': 829, 'away': 62, 'hospital': 345, 'step': 733, 'government': 317, 'start': 728, 'sit': 691, 'wife': 843, 'floor': 286, 'career': 112, 'east': 216, 'system': 757, 'sense': 668, 'without': 849, 'bank': 68, 'thought': 779, 'board': 90, 'network': 488, 'describe': 191, 'decide': 184, 'fly': 287, 'happy': 331, 'message': 454, 'pretty': 572, 'red': 616, 'expert': 255, 'always': 31, 'cold': 143, 'avoid': 61, 'head': 333, 'easy': 217, 'federal': 267, 'wind': 845, 'seem': 664, 'owner': 521, 'suddenly': 750, 'source': 712, 'democrat': 189, 'rise': 640, 'reveal': 637, 'program': 582, 'resource': 630, 'take': 759, 'hold': 342, 'member': 451, 'skill': 696, 'record': 615, 'west': 835, 'growth': 323, 'pay': 535, 'day': 180, 'know': 388, 'improve': 361, 'son': 707, 'raise': 599, 'finish': 280, 'better': 81, 'light': 412, 'behavior': 76, 'painting': 523, 'create': 169, 'really': 609, 'grow': 322, 'dark': 177, 'whole': 840, 'well': 834, 'oil': 508, 'scene': 651, 'action': 7, 'prepare': 568, 'live': 419, 'report': 625, 'event': 242}
Feature Matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3938306 stored elements and shape (20000, 867)>
  Coords	Values
  (0, 762)	1
  (0, 197)	3
  (0, 737)	2
  (0, 21)	1
  (0, 398)	1
  (0, 335)	2
  (0, 520)	1
  (0, 160)	1
  (0, 603)	1
  (0, 198)	1
  (0, 862)	1
  (0, 272)	1
  (0, 566)	2
  (0, 266)	3
  (0, 356)	1
  (0, 585)	1
  (0, 661)	1
  (0, 318)	2
  (0, 481)	1
  (0, 499)	1
  (0, 264)	1
  (0, 738)	1
  (0, 394)	1
  (0, 485)	1
  (0, 86)	1
  :	:
  (19999, 782)	1
  (19999, 517)	1
  (19999, 192)	1
  (19999, 366)	1
  (19999, 601)	1
  (19999, 10)	1
  (19999, 561)	2
  (19999, 95)	1
  (19999, 309)	1
  (19999, 119)	1
  (19999, 557)	1
  (19999, 357)	1
  (19999, 512)	1
  (19999, 141)	1
  (19999, 18)	1
  (19999, 691)	1
  (19999, 68)	1
  (19999, 287)	1
  (19999, 31)	1
  (19999, 61)	1
  (19999, 267)	1
  (19999, 582)	1
  (19999, 599)	1
  (19999, 81)	1
  (19999, 834)	1

In [ ]:
#TF-IDF vectorizer === Termed Frequency Inverse document frequency vectorizer

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['final_text'])
print(X)

In [52]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,df.label,test_size=0.2,random_state=42)

In [53]:
lr=LogisticRegression()

In [54]:
lr.fit(x_train,y_train)

LogisticRegression()

In [55]:
y_test

10650    1
2041     1
8668     0
1114     1
13902    1
        ..
4073     1
7442     0
9999     0
1870     1
15196    0
Name: label, Length: 4000, dtype: int64

In [56]:
y_pred=lr.predict(x_test)

In [57]:
y_pred

array([0, 1, 0, ..., 1, 0, 1], shape=(4000,))

In [58]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.506

In [59]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.51      0.51      2029
           1       0.50      0.50      0.50      1971

    accuracy                           0.51      4000
   macro avg       0.51      0.51      0.51      4000
weighted avg       0.51      0.51      0.51      4000

In [60]:
query = input("User input: ")

def predict(query):
    query = clean_text(query)
    query_tokens = word_tokenize(query)
    query_no_stopwords = remove_stopwords(query_tokens)
    query_lemmatized = lemmatization(query_no_stopwords)
    query_final = " ".join(query_lemmatized)

    query_vectorized = tfidf.transform([query_final]) 

    prediction = lr.predict(query_vectorized)
    print(prediction)
    return "Real" if prediction[0] == 1 else "Fake"


result = predict(query)
print("Prediction:", result)

[0]
Prediction: Fake